[package]
name = "game_of_life"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
clearscreen = "2.0.1"
sdl2 = "0.35.2"
clap = { version = "4.3.24", features = ["derive"] }
